spring:
  application:
    name: lapa-pomoshi

  datasource:
    url: jdbc:postgresql://db:5432/paw_of_help
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:liquibase/db-changelog.xml

logging:
  level:
    liquibase: DEBUG
    org.springframework.boot.autoconfigure.liquibase: DEBUG

jwt:
  secret: "ChangeMe_UseAtLeast256BitsSecretKeyForProductionEnvironment1234567890"
  expiration-ms: 86400000

server:
  port: 8081